#!/bin/bash
# push-hosts.sh — Generated by Terraform templatefile().
# Pushes a populated /etc/hosts to every node so they resolve
# each other by hostname using private IPs.

set -euo pipefail

SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ${ssh_private_key_path}"

HOSTS_BLOCK="# kubeadm cluster nodes\n${controlplane_ip} controlplane\n%{ for i, ip in worker_private_ips ~}${ip} node0${i + 1}\n%{ endfor ~}"

ALL_PUBLIC_IPS=("${controlplane_pub_ip}" %{ for ip in worker_public_ips ~}"${ip}" %{ endfor ~})

echo "==> Waiting for nodes to be SSH-ready..."
for pub_ip in "$${ALL_PUBLIC_IPS[@]}"; do
  for attempt in $(seq 1 20); do
    if ssh $SSH_OPTS root@"$pub_ip" true 2>/dev/null; then
      echo "    $pub_ip is ready"
      break
    fi
    echo "    $pub_ip not ready yet (attempt $attempt/20), retrying in 15s..."
    sleep 15
  done
done

echo "==> Pushing /etc/hosts entries to all nodes..."
for pub_ip in "$${ALL_PUBLIC_IPS[@]}"; do
  ssh $SSH_OPTS root@"$pub_ip" "printf '$HOSTS_BLOCK' | tee -a /etc/hosts"
  echo "    Done: $pub_ip"
done

echo "==> /etc/hosts populated on all nodes."
